version: "3.8"

services:
  mongodb:
    image: mongo:6.0
    restart: on-failure
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongodb_data:/data/db
    ports:
      - "${MONGODB_PORT}:27017"

volumes:
  mongodb_data:
